{% set name = "tree_sitter" %}
{% set version = "0.25.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: cd761ad0e4d1fc88a4b1b8083bae06d4f973acf6f5f29bbf13ea9609c1dec9c1

build:
  script:
    - export CFLAGS="-D_BSD_SOURCE"  # [unix]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  skip: true  # [py<310]
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools >=43
  run:
    - python

test:
  imports:
    - tree_sitter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tree-sitter/py-tree-sitter
  summary: Python bindings to the Tree-sitter parsing library
  license: MIT and EPL-2.0
  license_file:
    - LICENSE
    - tree_sitter/core/lib/src/unicode/LICENSE

extra:
  recipe-maintainers:
    - danielnachun
    - thewchan
    - davidbrochart
