{% set name = "tree_sitter" %}
{% set version = "0.20.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tree_sitter-{{ version }}.tar.gz
  sha256: 6adb123e2f3e56399bbf2359924633c882cc40ee8344885200bca0922f713be5

build:
  skip: true  # [py<33]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=43.0.0
    - wheel >=0.36.2
  run:
    - python

test:
  imports:
    - tree_sitter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tree-sitter/py-tree-sitter
  summary: Python bindings to the Tree-sitter parsing library
  license: MIT and EPL-2.0
  license_file:
    - LICENSE
    - tree_sitter/core/lib/src/unicode/LICENSE

extra:
  recipe-maintainers:
    - thewchan
