{% set name = "tree_sitter" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: c74ec9eff30e0c5b9f00ee578cca64df322b9885c8a15364a2c537f485abcc77

build:
  skip: true  # [py<33 and py>311]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=43.0.0
    - wheel >=0.36.2
  run:
    - python

test:
  imports:
    - tree_sitter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tree-sitter/py-tree-sitter
  summary: Python bindings to the Tree-sitter parsing library
  license: MIT and EPL-2.0
  license_file:
    - LICENSE
    - tree_sitter/core/lib/src/unicode/LICENSE

extra:
  recipe-maintainers:
    - thewchan
