{% set name = "tree_sitter" %}
{% set version = "0.23.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 66bae8dd47f1fed7bdef816115146d3a41c39b5c482d7bad36d9ba1def088450

build:
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools >=43
  run:
    - python

test:
  imports:
    - tree_sitter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tree-sitter/py-tree-sitter
  summary: Python bindings to the Tree-sitter parsing library
  license: MIT and EPL-2.0
  license_file:
    - LICENSE
    - tree_sitter/core/lib/src/unicode/LICENSE

extra:
  recipe-maintainers:
    - danielnachun
    - thewchan
    - davidbrochart
